### ISSUE TITLE
Launching Mupen64plus GLES3 or Parallel64 Retroarch cores through Daijisho causes inputs to not register

### ISSUE THREAD

**Issue by AncientCarthage** [TapiocaFox/Daijishou#181] opened 2023-01-11 19:49 UTC
I encountered this glitch two days ago, if you launch a game through Daijisho when M64P GLES3 or Parallel64 is selected, the controls on your device will no lomger register, or if they do, they will register in an extremely delayed manner. This effect persists even when not launching a game through Daijisho, as long as you do it once the effect will persist.  The only fix I've found is to completely uninstall retroarch and all of its installation folders, then reinstalling it.

**Comment by Jetup13** [comment] 2023-01-12 00:56
This is a known issue when launching into the N64 corrs from a front-end. Here's the issue being mentioned back in [2016](https://github.com/libretro/parallel-n64/issues/336)

Launching the Retroarch Quick Menu restores the controls. I'll recommend creating an [touch screen overlay](https://valent-in.github.io/retropad-editor/)

**Comment by stuffu** [comment] 2023-02-17 11:29
I also encountered this, I guess the issue is in RA rather than the frontend or emulator itself?

**Comment by magneticchen** [comment] 2023-03-06 22:10
> I also encountered this, I guess the issue is in RA rather than the frontend or emulator itself?

Seems like it.

**Comment by stuffu** [comment] 2023-03-21 07:54
@AncientCarthage Trying to narrow it down with the help from RA, which device are you using when you experience the issues with inputs not registering? I have a Retroid Pocket 3+ myself.

**Comment by stuffu** [comment] 2023-03-21 07:59
@magneticchen It could be device specific or a Daijishou issue, do you have any possibility to test this on a different device than Retroid Pocket? https://github.com/libretro/RetroArch/issues/15109#issuecomment-1477056234

**Comment by magneticchen** [comment] 2023-03-26 22:18
Hello. I've tried it myself seems like the core has several issues with several games.

**Comment by delta62** [comment] 2023-07-07 05:33
I'm seeing similar problems on an Odin Lite, Android 11. I [posted](https://github.com/libretro/RetroArch/issues/15109#issuecomment-1624770298) detailed testing information in the linked thread. From what I can tell this is not a Daijishou issue since I can repro the exact same problem with LaunchBox. I'm wondering for others experiencing this problem - do other front ends have the same issue with RA?

**Comment by Jetup13** [comment] 2023-07-19 18:52
The issue is most likely how RetroArch starts to recognize a controller connected. It's inconsistent between games & controllers on the N64 cores when launched from a front-end. 

Here's the apparent fix:

> Open RetroArch by itself > Settings > Input > Polling Behavior > Early > Save Configuration 

Or if you want to save it per core

> RetroArch Quick Menu > RetroArch Main Menu > Settings > Input > Polling Behavior > Early > RetroArch Quick Menu > Overrides > Save Core Override 

I tested it on my end with Rogue Squadron (since that's the only game I can get to always reproduce the issue) and it seems to work. 

If your still following this issue try the setting mentioned above and see if it works.

**Comment by Jetup13** [comment] 2023-11-21 04:59
Closing this issue as the above message fixes the issue when launched from a frontend

**Closed by Jetup13** 2023-11-21 04:59 UTC
Labels: platforms and players, hanging
